import { Router } from "express";
import { db, nextId } from "../db.js";
import { requireAuth, requireAdminScope } from "../auth.js";
import { SNAPSHOT_METRICS, captureDailySnapshot, utcDateString } from "../snapshots.js";
import { refreshSilverMedalistMatches } from "../lib/silverMedalist.js";

export const adminSnapshotsRouter = Router();

/* Platform-wide view of daily_snapshots - every metric/dimension, not just one employer's own.
   Finance/support scopes can already see revenue/ops numbers elsewhere in the admin console, so
   they're allowed here too; a plain "readonly" admin also passes since this is a GET. */
adminSnapshotsRouter.get("/snapshots", requireAuth, requireAdminScope("finance", "support"), (req, res) => {
  const days = Math.min(365, Math.max(1, Number(req.query.days) || 30));
  const metric = req.query.metric;
  if (metric && !SNAPSHOT_METRICS.includes(metric)) return res.status(400).json({ error: "Unknown metric." });
  const rows = db.prepare(
    `SELECT date, metric, dimension, value FROM daily_snapshots
     WHERE date >= date('now', ?) ${metric ? "AND metric = ?" : ""}
     ORDER BY date ASC`
  ).all(...(metric ? [`-${days} days`, metric] : [`-${days} days`]));
  res.json({ days, snapshots: rows });
});

/* Priority-4 #6 - callable for admin/tests: the weekly batch also runs on boot and every 7 days
   (server/index.js), but a test run (or an impatient admin) shouldn't have to wait a week or
   restart the server to see it recompute. */
adminSnapshotsRouter.post("/silver-medalist-matches/refresh", requireAuth, requireAdminScope(), (req, res) => {
  const result = refreshSilverMedalistMatches();
  res.json(result);
});

/* Priority-5 admin CRUD sweep: silver-medalist matches are entirely system-generated (the weekly
   batch + the refresh button above), so there's no admin Create/Update - just a platform-wide Read
   (across every seeker/employer, unlike the employer-scoped GET in employers.js) and a manual
   Delete, for a moderator clearing a stale/bad match out of the queue. */
function serializeAdminSilverMedalistMatch(row) {
  return {
    id: row.id, seekerId: row.seeker_id, jobId: row.job_id, employerId: row.employer_id,
    overlapScore: row.overlap_score, matchedAt: row.matched_at, notifiedAt: row.notified_at, dismissedAt: row.dismissed_at,
  };
}
adminSnapshotsRouter.get("/silver-medalist-matches", requireAuth, requireAdminScope("support", "moderator"), (req, res) => {
  const rows = db.prepare("SELECT * FROM silver_medalist_matches ORDER BY matched_at DESC LIMIT 500").all();
  res.json({ matches: rows.map(serializeAdminSilverMedalistMatch) });
});
adminSnapshotsRouter.delete("/silver-medalist-matches/:id", requireAuth, requireAdminScope("moderator"), (req, res) => {
  const row = db.prepare("SELECT * FROM silver_medalist_matches WHERE id = ?").get(req.params.id);
  if (!row) return res.status(404).json({ error: "Not found." });
  db.prepare("DELETE FROM silver_medalist_matches WHERE id = ?").run(req.params.id);
  db.prepare("INSERT INTO activity_log (id, action, text, icon, actor) VALUES (?, 'admin.silverMedalistDelete', ?, 'trash', ?)")
    .run(nextId("l", "activity_log"), `Removed a silver-medalist match`, `${req.user.name} (${req.user.role})`);
  res.json({ ok: true });
});

/* Daily snapshots: system-generated by the nightly cron + boot backfill (server/index.js). No
   admin Update (a snapshot value is a historical fact, not an editable field) - just a manual
   re-capture of today's row, for when an admin doesn't want to wait for the next cron tick. */
adminSnapshotsRouter.post("/snapshots/recapture", requireAuth, requireAdminScope("finance", "support"), (req, res) => {
  const date = utcDateString(0);
  captureDailySnapshot(date);
  res.json({ ok: true, date });
});
