export const SEED_EMPLOYERS=[
  {id:"e1",name:"PCL Construction",mark:"bolt",a:"#B45309",b:"#FFF7EC",industry:"Construction",city:"Calgary",prov:"AB",size:"5,000+",rating:4.2,verified:true,owner:"hr@pcl.com",about:"Canada's largest general contractor, employee-owned since 1977. We build hospitals, transit hubs and industrial plants in every province, and we train more apprentices than any other builder in the country.",founded:1906,site:"pcl.com",plan:"Enterprise"},
  {id:"e2",name:"Sinai Health",mark:"cross",a:"#0F5C8C",b:"#EAF4FA",industry:"Healthcare",city:"Toronto",prov:"ON",size:"5,000+",rating:4.4,verified:true,owner:"careers@sinai.ca",about:"An academic health science centre with a national reputation for patient-centred care, teaching and research across acute, complex and community settings.",founded:1923,site:"sinaihealth.ca",plan:"Growth"},
  {id:"e3",name:"Day & Ross",mark:"road",a:"#B02A26",b:"#FDEEED",industry:"Transportation",city:"Moncton",prov:"NB",size:"5,000+",rating:3.9,verified:true,owner:"drive@dayross.ca",about:"One of Canada's largest transportation and logistics providers, moving freight across North America since 1950 with a fleet of more than 4,000 power units.",founded:1950,site:"dayross.com",plan:"Growth"},
  {id:"e4",name:"Loblaw Companies",mark:"basket",a:"#0B6B3A",b:"#EAF6EF",industry:"Retail",city:"Brampton",prov:"ON",size:"10,000+",rating:3.8,verified:true,owner:"talent@loblaw.ca",about:"Canada's food and pharmacy leader, serving millions of Canadians each week through more than 2,400 stores and a national supply chain network.",founded:1919,site:"loblaw.ca",plan:"Growth"},
  {id:"e5",name:"Cactus Restaurants",mark:"flame",a:"#8A2B36",b:"#FCEEF0",industry:"Hospitality",city:"Vancouver",prov:"BC",size:"1,000-5,000",rating:4.1,verified:false,owner:"jobs@cactus.ca",about:"A premium casual restaurant group known for developing hospitality careers from dishpit to general manager, with structured training at every level.",founded:1988,site:"cactusrestaurants.ca",plan:"Growth"},
  {id:"e6",name:"Linamar",mark:"gear",a:"#1F4E79",b:"#EAF1F8",industry:"Manufacturing",city:"Guelph",prov:"ON",size:"5,000+",rating:3.9,verified:true,owner:"hr@linamar.com",about:"Advanced manufacturer producing precision components for global mobility, industrial and agricultural markets from 60 plants worldwide.",founded:1966,site:"linamar.com",plan:"Enterprise"},
  {id:"e7",name:"Sun Life",mark:"arc",a:"#B8860B",b:"#FDF6E3",industry:"Finance",city:"Toronto",prov:"ON",size:"10,000+",rating:4.3,verified:true,owner:"careers@sunlife.ca",about:"International financial services organisation providing insurance, wealth and asset management to individuals and corporate clients in 27 markets.",founded:1865,site:"sunlife.ca",plan:"Enterprise"},
  {id:"e8",name:"Toronto DSB",mark:"book",a:"#5B2E8C",b:"#F2EBFA",industry:"Education",city:"Toronto",prov:"ON",size:"10,000+",rating:4.0,verified:true,owner:"hr@tdsb.on.ca",about:"The largest school board in Canada, serving over 235,000 students across 583 schools with a workforce of teachers, educators and support staff.",founded:1998,site:"tdsb.on.ca",plan:"Growth"},
  {id:"e9",name:"Northbyte Systems",mark:"hex",a:"#0B7A4B",b:"#E9F7F1",industry:"Technology",city:"Ottawa",prov:"ON",size:"1,000-5,000",rating:4.5,verified:true,owner:"talent@northbyte.ca",about:"Canadian software company building commerce and logistics infrastructure used by thousands of small businesses across North America.",founded:2011,site:"northbyte.ca",plan:"Growth"},
  {id:"e10",name:"Cavendish Farms",mark:"leafm",a:"#3C6E2A",b:"#EDF6E9",industry:"Agriculture",city:"Charlottetown",prov:"PE",size:"1,000-5,000",rating:3.7,verified:false,owner:"jobs@cavendish.ca",about:"Family-owned food processor and one of Atlantic Canada's largest agricultural employers, working with more than 600 partner farms.",founded:1980,site:"cavendishfarms.com",plan:"Growth"},
  {id:"e11",name:"GardaWorld",mark:"shield",a:"#28404F",b:"#EDF1F4",industry:"Security",city:"Montreal",prov:"QC",size:"10,000+",rating:3.6,verified:false,owner:"hiring@garda.ca",about:"The world's largest privately owned security services company, headquartered in Montreal with operations across Canada and 45 other countries.",founded:1995,site:"garda.com",plan:"Free"},
  {id:"e12",name:"Bird Construction",mark:"chart",a:"#A14A18",b:"#FCEFE7",industry:"Construction",city:"Mississauga",prov:"ON",size:"1,000-5,000",rating:4.0,verified:true,owner:"careers@bird.ca",about:"A leading Canadian construction company delivering industrial, buildings and infrastructure projects in every province and territory.",founded:1920,site:"bird.ca",plan:"Growth"},
];
