import { _ago } from "../../helpers/utils.js";

/* Employee expense claims — reimbursement flow (submit → approve/reject → pay).
   Category taxonomy matches CRA T2200 employment-expense buckets. */
export const HR_EXPENSES_SEED=[
  {id:"xp1",employee:"emp3",category:"Travel",merchant:"Air Canada",amount:684.50,currency:"CAD",description:"Client site visit YYZ→YYC round trip",date:"2026-08-14",status:"paid",submitted:_ago(19*864e5),approvedBy:"emp1",approvedAt:_ago(18*864e5),paidAt:_ago(11*864e5),rejectReason:null,reimburseVia:"next-payroll",receiptUrl:"receipt-aircanada-684.pdf"},
  {id:"xp2",employee:"emp5",category:"Training",merchant:"Alberta Construction Safety Association",amount:1245.00,currency:"CAD",description:"NCSO certification renewal course + exam",date:"2026-08-08",status:"paid",submitted:_ago(25*864e5),approvedBy:"emp4",approvedAt:_ago(24*864e5),paidAt:_ago(17*864e5),rejectReason:null,reimburseVia:"next-payroll",receiptUrl:"receipt-acsa-1245.pdf"},
  {id:"xp3",employee:"emp3",category:"Meals",merchant:"The Keg Steakhouse",amount:214.80,currency:"CAD",description:"Client dinner — Foothills project close-out",date:"2026-08-21",status:"approved",submitted:_ago(6*864e5),approvedBy:"emp1",approvedAt:_ago(5*864e5),paidAt:null,rejectReason:null,reimburseVia:"next-payroll",receiptUrl:"receipt-keg-214.pdf"},
  {id:"xp4",employee:"emp6",category:"Tools & Equipment",merchant:"Home Depot",amount:389.00,currency:"CAD",description:"Klein digital multimeter replacement",date:"2026-08-22",status:"submitted",submitted:_ago(5*864e5),approvedBy:null,approvedAt:null,paidAt:null,rejectReason:null,reimburseVia:"next-payroll",receiptUrl:"receipt-homedepot-389.pdf"},
  {id:"xp5",employee:"emp9",category:"Mileage",merchant:"Personal vehicle",amount:158.60,currency:"CAD",description:"Site visits — 340km @ CRA rate $0.68/km — 3 sites in one day",date:"2026-08-24",status:"submitted",submitted:_ago(3*864e5),approvedBy:null,approvedAt:null,paidAt:null,rejectReason:null,reimburseVia:"next-payroll",receiptUrl:null},
  {id:"xp6",employee:"emp8",category:"Software",merchant:"Adobe Systems",amount:79.99,currency:"CAD",description:"Adobe Creative Cloud monthly — invoiced to personal card",date:"2026-08-01",status:"rejected",submitted:_ago(28*864e5),approvedBy:"emp7",approvedAt:_ago(26*864e5),paidAt:null,rejectReason:"Company license already covers this — please use IT-provisioned account",reimburseVia:"next-payroll",receiptUrl:"receipt-adobe-79.pdf"},
  {id:"xp7",employee:"emp2",category:"Home Office",merchant:"Amazon.ca",amount:329.99,currency:"CAD",description:"Ergonomic chair for home office (per WFH policy)",date:"2026-08-18",status:"submitted",submitted:_ago(9*864e5),approvedBy:null,approvedAt:null,paidAt:null,rejectReason:null,reimburseVia:"next-payroll",receiptUrl:"receipt-amazon-329.pdf"},
];
