import { EXTRA_JOBS } from "./jobsExtra.js";

const J=(id,t,e,cat,city,prov,type,mode,lo,hi,unit,vac,exp,edu,dl,posted,views,urgent,featured,skills,perks,desc,duties,reqs,how)=>
  ({id,t,e,cat,city,prov,type,mode,lo,hi,unit,vac,exp,edu,dl,posted,views,urgent,featured,skills,perks,desc,duties,reqs,how,status:"live",flagged:false});

/* The thirty hand-written flagship postings. EXTRA_JOBS appends the generated volume that brings
   the published board to 120 listings — see jobsExtra.js. */
const FLAGSHIP_JOBS=[
 J("j1","Red Seal Journeyperson Electrician","e1","trades","Calgary","AB","Full Time","On-site",44,52,"hr",6,"3+ years","Red Seal Certificate",9,"1 day ago",1840,true,true,
  ["Red Seal","Commercial Wiring","Blueprint Reading","CSA Code","Conduit Bending"],
  ["Overtime after 8 hours daily","RRSP matching to 5%","Full health, dental and vision","$1,200 annual tool allowance","Employer-paid safety training"],
  "Join our Calgary commercial division installing and terminating electrical systems on large institutional and industrial projects. You will work with a crew of journeypersons and apprentices under a site foreman, with year-round work and consistent overtime.",
  ["Install, alter and repair electrical systems to CSA and Alberta code","Read and interpret blueprints, schematics and layout drawings","Terminate and test panels, transformers and distribution equipment","Mentor apprentices and enforce daily safety practices","Complete field reports and material requisitions"],
  ["Valid Alberta Red Seal or Interprovincial journeyperson certificate","Minimum 3 years commercial or industrial experience","Ability to lift 50 lb and work at heights","Valid driver's licence and reliable transportation","CSTS-2020 and Fall Protection tickets an asset"],
  "Apply through NorthHire with your resume and Red Seal certificate. Shortlisted candidates are contacted within 3 business days for a site interview."),
 J("j2","Registered Nurse — Medical Surgical","e2","health","Toronto","ON","Full Time","On-site",39,56,"hr",12,"1+ years","BScN + CNO Registration",14,"2 days ago",2310,true,true,
  ["CNO Registration","BLS","Patient Assessment","IV Therapy","Electronic Charting"],
  ["HOOPP defined benefit pension","Shift and weekend premiums","4 weeks vacation to start","$1,500 annual education fund","Subsidised on-site parking"],
  "Provide direct nursing care on a 34-bed medical surgical unit within a fully accredited academic hospital. New graduates are supported through a structured 12-week mentorship with a dedicated clinical educator.",
  ["Assess, plan, implement and evaluate patient care plans","Administer medications and monitor therapeutic response","Collaborate with physicians, allied health and families","Document accurately in the electronic health record","Participate in unit quality improvement work"],
  ["Current registration in good standing with the College of Nurses of Ontario","BScN from an accredited program","Current BLS certification","Availability for 12-hour rotating shifts including weekends","Medical surgical experience preferred, not required"],
  "Submit your application with proof of CNO registration. Interviews are held weekly with conditional offers within 5 business days."),
 J("j3","AZ Class 1 Long Haul Driver","e3","transport","Moncton","NB","Full Time","On-site",0.62,0.74,"mi",20,"2+ years","Class 1 / AZ Licence",21,"3 days ago",1520,true,false,
  ["Class 1 Licence","Air Brakes","ELD Logs","Cross-border","Pre-trip Inspection"],
  ["$5,000 sign-on bonus over 12 months","Benefits effective day one","New 2024 tractors with APU","Paid orientation and training","Home every weekend guaranteed"],
  "Run dedicated lanes between Atlantic Canada, Ontario and the US northeast with modern equipment. Guaranteed home time every weekend and a predictable schedule.",
  ["Operate a tractor-trailer safely across Canada and the United States","Complete pre-trip and post-trip inspections","Maintain accurate electronic logs under HOS rules","Secure and verify freight before departure","Communicate delays promptly with dispatch"],
  ["Valid Class 1 / AZ licence with clean abstract","Minimum 2 years verifiable long haul experience","Ability to cross the US border, FAST card an asset","Clean CVOR and criminal record check","Comfortable with electronic logging devices"],
  "Apply online and a recruiter calls within 48 hours to review lanes, pay and start dates. Road test at your nearest terminal."),
 J("j4","Grocery Store Assistant Manager","e4","retail","Mississauga","ON","Full Time","On-site",52000,64000,"yr",4,"2+ years","High School Diploma",12,"4 days ago",980,false,true,
  ["Team Leadership","Inventory Control","Scheduling","Customer Service","Loss Prevention"],
  ["10% colleague discount","Annual performance bonus","Pension with company match","Extended health and dental","Tuition reimbursement"],
  "Support the store manager in running a high-volume grocery location serving over 20,000 customers weekly. Hands-on leadership with a clear path to store manager within 24 months.",
  ["Lead and schedule a team of 40+ associates across departments","Manage inventory levels, ordering and shrink control","Resolve customer concerns and uphold service standards","Ensure food safety and health regulation compliance","Support hiring, onboarding and performance coaching"],
  ["2+ years retail supervisory experience, grocery preferred","Availability for evenings, weekends and holidays","Strong problem solving and communication skills","Comfortable with inventory and scheduling software","Food Handler Certification or willingness to obtain"],
  "Apply with your resume. Qualified applicants complete a short online assessment followed by two interviews."),
 J("j5","Line Cook — Full Time","e5","hosp","Vancouver","BC","Full Time","On-site",22,28,"hr",5,"1+ years","No formal education required",7,"1 day ago",1120,true,false,
  ["Grill Station","Food Safe Level 1","Knife Skills","Portion Control","Kitchen Sanitation"],
  ["Kitchen tip pool, roughly $4-6/hr extra","Staff meal every shift","50% dining discount","Extended health after 3 months","Clear path to sous chef"],
  "Work a station in a scratch kitchen turning 300+ covers a night. We promote from within and most of our sous chefs started on the line. Tips are pooled with the kitchen.",
  ["Prepare and plate dishes to recipe specification","Maintain station cleanliness and organisation","Monitor food quality, temperature and portioning","Assist with prep, receiving and inventory counts","Support other stations during peak service"],
  ["1+ year line cook experience in a high-volume kitchen","FOODSAFE Level 1 certification","Ability to stand for 8+ hours in a hot environment","Available evenings and weekends","Team-first attitude under pressure"],
  "Apply online, then attend an open interview held Tuesdays and Thursdays between 2pm and 4pm at the restaurant."),
 J("j6","CNC Machinist — Afternoon Shift","e6","factory","Guelph","ON","Full Time","On-site",28,36,"hr",8,"2+ years","Machinist Certificate",18,"5 days ago",760,false,false,
  ["CNC Operation","G-Code","Blueprint Reading","GD&T","Micrometers"],
  ["$2.00/hr afternoon premium","Profit sharing","Company pension contribution","Full benefits after 90 days","Paid skills upgrading"],
  "Set up and operate CNC lathes and machining centres producing precision automotive components. Afternoon shift carries a premium and the plant runs year-round.",
  ["Set up, program and operate CNC turning and milling equipment","Inspect finished parts with precision measuring instruments","Perform first-article and in-process quality checks","Complete preventive maintenance on assigned machines","Record production data accurately"],
  ["2+ years CNC machining experience","Ability to read blueprints and apply GD&T","Comfortable with Fanuc or Siemens controls","Steel-toed safety footwear","Available afternoon shift, Monday to Friday"],
  "Submit your resume. Candidates are invited for a practical shop-floor assessment."),
 J("j7","Administrative Assistant","e7","admin","Toronto","ON","Full Time","Hybrid",48000,58000,"yr",2,"1+ years","College Diploma",11,"2 days ago",1440,false,false,
  ["MS Office","Calendar Management","Minute Taking","Expense Reporting","Confidentiality"],
  ["Hybrid after month one","Defined contribution pension","Wellness spending account","Employee share purchase plan","3 weeks vacation"],
  "Provide administrative support to a team of eight advisors in a downtown office. Hybrid schedule with three days in office and two remote after your first month.",
  ["Manage complex calendars and coordinate meetings","Prepare correspondence, reports and presentations","Process expense claims and invoices","Maintain confidential client files","Coordinate travel and team events"],
  ["1+ years administrative experience","Post-secondary diploma in business administration or related","Advanced Outlook, Word and Excel skills","Excellent written and verbal communication","Discretion handling confidential information"],
  "Apply with a resume and short cover note. Shortlisted candidates complete a brief Excel assessment."),
 J("j8","Early Childhood Educator (RECE)","e8","edu","Toronto","ON","Full Time","On-site",25,33,"hr",9,"Entry level welcome","ECE Diploma + Registration",16,"3 days ago",1050,false,true,
  ["RECE Registration","Child Development","Behaviour Guidance","Program Planning","First Aid"],
  ["OMERS pension plan","Paid PA days and school breaks","Extended health and dental","Paid professional development","No evening or weekend shifts"],
  "Deliver play-based early learning programs in a licensed before and after school setting. Consistent weekday hours and paid professional development throughout the year.",
  ["Plan and deliver age-appropriate learning experiences","Observe and document children's development","Build positive relationships with families","Maintain a safe, clean and inclusive environment","Follow all licensing and health regulations"],
  ["ECE diploma and registration with the College of ECE","Valid Standard First Aid and CPR-C","Clear vulnerable sector police check","Up-to-date immunisation record","Patience, warmth and strong communication"],
  "Apply with your resume and proof of RECE registration. Interviews include a short classroom observation."),
 J("j9","Warehouse Associate — Nights","e4","factory","Surrey","BC","Full Time","On-site",23,27,"hr",15,"No experience required","No formal education required",6,"12 hours ago",2140,true,false,
  ["Order Picking","RF Scanner","Pallet Jack","Team Work","Lifting 50 lb"],
  ["$1.50/hr night premium","Permanent after 480 hours","Colleague discount","Benefits after 6 months","Free on-site parking"],
  "Pick, pack and load orders in a temperature-controlled distribution centre. Full training provided, no experience necessary, permanent position after 480 hours.",
  ["Pick orders accurately using an RF scanner","Palletise and wrap product for shipping","Operate manual and electric pallet jacks","Maintain a clean and safe work area","Meet daily productivity and accuracy targets"],
  ["Ability to lift up to 50 lb repeatedly","Comfortable working in cooler temperatures","Available night shift, Sunday to Thursday","Reliable attendance and punctuality","Steel-toed boots required"],
  "Apply online and attend a same-week hiring session. Bring photo ID and SIN. Start dates every Monday."),
 J("j10","Bilingual Customer Service Representative","e7","retail","Montreal","QC","Full Time","Remote",23,28,"hr",10,"Entry level welcome","High School Diploma",13,"1 day ago",1690,false,true,
  ["Bilingual FR/EN","Active Listening","CRM Software","Conflict Resolution","Data Entry"],
  ["Fully remote in Quebec and Ontario","Equipment provided","4 weeks paid training","Group insurance from day one","Annual performance bonus"],
  "Support customers by phone and chat in French and English from home. Equipment provided and paid training runs four weeks with no weekend shifts during training.",
  ["Answer inbound calls and chats in French and English","Resolve billing, coverage and account enquiries","Document interactions accurately in the CRM","Escalate complex cases to specialist teams","Meet quality and service level targets"],
  ["Fluent written and spoken French and English","High school diploma or equivalent","Reliable high-speed internet at home","Quiet dedicated workspace","Available rotating shifts between 8am and 8pm"],
  "Apply online and complete a short bilingual language assessment. Virtual interviews within one week."),
 J("j11","Heavy Duty Equipment Technician","e12","trades","Edmonton","AB","Full Time","On-site",42,50,"hr",4,"3+ years","Journeyperson Certificate",20,"6 days ago",640,false,false,
  ["Hydraulics","Diesel Engines","Preventive Maintenance","Welding","Diagnostics"],
  ["Company service truck","Overtime and call-out pay","RRSP matching","Full family benefits","Annual boot and tool allowance"],
  "Maintain and repair heavy construction equipment across active Alberta job sites and in our Edmonton shop. Company truck and full tooling provided for field service.",
  ["Diagnose and repair hydraulic, electrical and diesel systems","Perform scheduled preventive maintenance","Complete field service calls to active sites","Document all work orders and parts used","Maintain shop safety and cleanliness standards"],
  ["Heavy Duty Equipment Technician journeyperson certificate","3+ years with construction equipment","Valid Class 5 driver's licence","Own hand tools","Willing to travel to sites within Alberta"],
  "Apply with your certificate. Interviews include a practical diagnostic assessment."),
 J("j12","Security Guard — Concierge","e11","security","Montreal","QC","Part Time","On-site",20,23,"hr",11,"Entry level welcome","Security Licence (BSP)",5,"2 days ago",890,true,false,
  ["BSP Licence","Access Control","Report Writing","Customer Service","CCTV Monitoring"],
  ["Uniform provided","Paid licence renewal","Flexible scheduling","Advancement to supervisor","Indoor climate-controlled post"],
  "Provide concierge and access control services in a downtown residential tower. Quiet indoor post with flexible part-time shifts that fit around studies or a second job.",
  ["Control building access and verify visitor credentials","Monitor CCTV and respond to alarms","Write clear and accurate incident reports","Assist residents with enquiries professionally","Conduct scheduled interior patrols"],
  ["Valid BSP security licence for Quebec","Working French required, English an asset","Clean criminal record","Professional presentation and communication","Available weekend day shifts"],
  "Apply online with your BSP licence number. Onboarding sessions run every Wednesday."),
 J("j13","Agricultural Equipment Operator","e10","agri","Charlottetown","PE","Seasonal","On-site",24,29,"hr",14,"1+ years","No formal education required",10,"4 days ago",520,false,false,
  ["Tractor Operation","Harvest Equipment","Basic Mechanics","Safety Compliance","Field Records"],
  ["Seasonal completion bonus","Overtime during harvest","Subsidised on-site housing","Returning worker priority","Meals during harvest"],
  "Operate planting and harvesting equipment across our Prince Edward Island potato operations. Seasonal contract April through November with strong prospects for returning.",
  ["Operate tractors, harvesters and support equipment","Perform daily equipment checks and greasing","Assist with field loading and transport","Follow crop protection and safety protocols","Record field activity and yields"],
  ["1+ year operating farm equipment","Valid driver's licence","Ability to work extended hours during harvest","Comfortable outdoors in all conditions","Mechanical aptitude an asset"],
  "Apply online. Housing assistance available for out-of-province applicants. Start dates begin in April."),
 J("j14","Full Stack Developer","e9","tech","Ottawa","ON","Full Time","Remote",105000,145000,"yr",3,"4+ years","Bachelor's Degree or equivalent",24,"1 day ago",3210,false,true,
  ["TypeScript","React","Node.js","PostgreSQL","REST APIs"],
  ["Fully remote within Canada","RRSP matching to 5%","Stock options","$3,000 annual learning budget","Home office allowance"],
  "Build merchant-facing commerce tools used by thousands of Canadian businesses. Fully remote with a strong engineering culture and real ownership from day one.",
  ["Design and ship full stack features end to end","Write well-tested, maintainable production code","Participate in code review and technical design","Collaborate with product and design partners","Support and monitor services you build"],
  ["4+ years professional software development","Strong TypeScript and React experience","Comfortable with relational databases and API design","Experience shipping to production at scale","Legally eligible to work in Canada"],
  "Apply with your resume and relevant links. Process is a screening call, a technical exercise and two interviews."),
 J("j15","Personal Support Worker (PSW)","e2","health","Hamilton","ON","Part Time","On-site",24,29,"hr",18,"Entry level welcome","PSW Certificate",8,"3 days ago",1380,true,false,
  ["PSW Certificate","Personal Care","Mobility Assistance","Documentation","Compassion"],
  ["Guaranteed minimum weekly hours","Evening and night premiums","Paid orientation","Pension eligibility","Free uniform allowance"],
  "Provide compassionate personal care to residents in a long-term care home. Flexible part-time shifts with the option to pick up extra hours and a guaranteed weekly minimum.",
  ["Assist residents with bathing, dressing and grooming","Support safe mobility and transfers","Serve meals and assist with feeding as needed","Report changes in condition to nursing staff","Document care provided each shift"],
  ["PSW certificate from a recognised Ontario program","Current vulnerable sector check","Standard First Aid and CPR","Up-to-date immunisations","Physically able to assist with transfers"],
  "Apply with your PSW certificate. Interviews are rolling with immediate start available."),
 J("j16","Insurance Claims Adjuster","e7","finance","Winnipeg","MB","Full Time","Hybrid",58000,72000,"yr",3,"2+ years","Bachelor's Degree or CIP",17,"5 days ago",710,false,false,
  ["Claims Handling","Policy Interpretation","Negotiation","Report Writing","CIP Designation"],
  ["Full CIP tuition coverage","Hybrid 2 days in office","Defined contribution pension","Annual bonus","Health spending account"],
  "Investigate, evaluate and settle property claims from first notice to closure, with structured support toward your CIP designation and tuition fully covered.",
  ["Investigate claims and determine coverage","Estimate damages and negotiate settlements","Communicate clearly with policyholders","Document files accurately and completely","Identify and refer potential fraud"],
  ["2+ years claims or insurance experience","Post-secondary degree or CIP progress","Strong analytical and negotiation skills","Provincial adjuster licence or eligibility","Valid driver's licence"],
  "Apply with your resume. Assessment includes a written claims scenario exercise."),
 J("j17","Housekeeping Room Attendant","e5","hosp","Banff","AB","Seasonal","On-site",21,24,"hr",22,"No experience required","No formal education required",4,"1 day ago",1230,true,false,
  ["Attention to Detail","Time Management","Cleaning Standards","Reliability","Guest Service"],
  ["Subsidised staff accommodation","Free staff shuttle and ski pass","Meal discounts","Seasonal completion bonus","Return-season priority"],
  "Clean and prepare guest rooms in a mountain resort property. Staff accommodation available on site at subsidised rates, ideal if you are relocating for the season.",
  ["Clean and reset guest rooms to brand standard","Restock amenities and linens","Report maintenance issues promptly","Handle lost and found items per policy","Maintain cart and storage organisation"],
  ["Ability to stand and walk for full shifts","Attention to detail and consistency","Reliable and punctual","Available weekends and holidays","No prior experience necessary"],
  "Apply online. Interviews are virtual and accommodation is confirmed before your start date."),
 J("j18","Sheet Metal Apprentice","e12","trades","Winnipeg","MB","Apprenticeship","On-site",22,31,"hr",6,"Entry level welcome","High School Diploma",15,"2 days ago",840,false,true,
  ["Hand Tools","Measuring","Fabrication","Safety Awareness","Willingness to Learn"],
  ["Employer-sponsored technical training","Guaranteed wage progression","Tool purchase program","Full benefits from day one","Journeyperson mentorship"],
  "Start a registered apprenticeship in sheet metal fabrication and installation. Earn while you learn with fully sponsored technical training and a wage increase at each level.",
  ["Assist journeypersons with layout, fabrication and installation","Learn to read shop drawings and specifications","Operate shears, brakes and hand tools safely","Maintain a clean and organised work area","Attend scheduled technical training blocks"],
  ["High school diploma with Grade 11 math","Mechanical aptitude and interest in the trade","Ability to lift 50 lb and work at heights","Valid driver's licence preferred","Committed to a 4-year apprenticeship"],
  "Apply with your high school transcript. Selected applicants complete an aptitude assessment and shop tour."),
 J("j19","Dental Receptionist","e2","admin","Halifax","NS","Part Time","On-site",22,27,"hr",2,"1+ years","High School Diploma",9,"4 days ago",560,false,false,
  ["Dental Software","Scheduling","Insurance Billing","Phone Etiquette","Patient Records"],
  ["No evening or weekend shifts","Dental benefits for family","Paid statutory holidays","Uniform allowance","Small supportive team"],
  "Be the first point of contact at a busy family dental practice. Friendly team, no evenings, and a consistent Tuesday to Friday schedule.",
  ["Greet patients and manage the daily schedule","Submit and follow up on insurance claims","Collect payments and reconcile daily totals","Maintain accurate patient records","Coordinate recall and appointment reminders"],
  ["1+ years reception experience, dental preferred","Familiarity with dental practice software an asset","Strong organisational and interpersonal skills","Professional and welcoming manner","Available Tuesday through Friday"],
  "Apply with your resume. The practice manager arranges a working interview with shortlisted candidates."),
 J("j20","Commercial Cleaner — Evenings","e11","security","Regina","SK","Part Time","On-site",19,22,"hr",13,"No experience required","No formal education required",6,"1 day ago",970,true,false,
  ["Floor Care","WHMIS","Attention to Detail","Independent Work","Reliability"],
  ["Consistent 5-day evening schedule","All supplies and equipment provided","Paid WHMIS certification","Mileage reimbursement","Advancement to site supervisor"],
  "Clean office buildings on an evening route across Regina. Consistent hours, independent work, full training with all supplies and equipment provided.",
  ["Vacuum, mop and sanitise assigned areas","Empty waste and recycling receptacles","Clean and restock washrooms","Report supply needs and maintenance issues","Secure the building at end of shift"],
  ["Ability to work independently with minimal supervision","Reliable transportation for an evening route","Clear criminal record check","WHMIS training or willingness to complete","Available Monday to Friday evenings"],
  "Apply online and complete a brief phone screen. Training is paid and starts within one week of hire."),
 J("j21","Sales Associate — Building Materials","e4","retail","London","ON","Full Time","On-site",21,26,"hr",7,"Entry level welcome","High School Diploma",11,"3 days ago",680,false,false,
  ["Product Knowledge","Customer Service","POS Systems","Forklift","Team Work"],
  ["Monthly sales commission","Colleague discount on materials","Forklift certification paid","Benefits after 3 months","Consistent weekday schedule"],
  "Help contractors and homeowners find the right materials for their projects. Extensive product training provided and commission on top of your hourly wage.",
  ["Advise customers on products and quantities","Prepare quotes and process orders","Maintain stock levels and displays","Assist with loading and yard organisation","Support inventory counts"],
  ["Customer-facing experience an asset","Ability to lift 50 lb","Comfortable using a computer for orders","Available weekends","Forklift certification an asset, training provided"],
  "Apply online or in person at the branch. Hiring decisions are typically made within one week."),
 J("j22","Payroll Administrator","e6","finance","Guelph","ON","Full Time","Hybrid",56000,68000,"yr",1,"2+ years","PCP Designation preferred",19,"6 days ago",490,false,false,
  ["Payroll Processing","Ceridian / ADP","Employment Standards","Reconciliation","Confidentiality"],
  ["Tuition support for PCP or CPM","Hybrid 2 days remote","Company pension contribution","Annual bonus","Extended health from day one"],
  "Process bi-weekly payroll for approximately 900 employees across multiple provinces, with full support toward your PCP or CPM designation.",
  ["Process end-to-end bi-weekly payroll accurately","Administer statutory deductions and remittances","Prepare ROEs, T4s and year-end filings","Respond to employee payroll enquiries","Reconcile payroll accounts monthly"],
  ["2+ years full-cycle payroll experience","Knowledge of provincial employment standards","PCP designation or actively pursuing","High accuracy and discretion","Advanced Excel skills"],
  "Apply with your resume noting your payroll systems experience. Assessment includes a reconciliation exercise."),
 J("j23","Welder / Fabricator (FCAW)","e6","trades","Hamilton","ON","Full Time","On-site",30,38,"hr",9,"2+ years","Welding Certificate",13,"2 days ago",1180,true,false,
  ["FCAW","MIG Welding","Blueprint Reading","Fit-up","CWB Ticket"],
  ["Shift premium for afternoons","Boot and jacket allowance","RRSP matching","Full benefits after 60 days","CWB recertification paid"],
  "Weld and fabricate structural assemblies in a modern shop with overhead cranes and positioners. CWB ticket testing paid for and steady year-round production.",
  ["Weld to CWB standards using FCAW and MIG processes","Fit up components from shop drawings","Inspect welds visually and correct defects","Operate overhead cranes and positioners safely","Maintain equipment and consumables"],
  ["2+ years structural or fabrication welding","Valid CWB ticket or ability to test within 30 days","Ability to read welding symbols and drawings","Comfortable lifting 50 lb","Steel-toed footwear and own hood"],
  "Apply with your ticket details. Shortlisted welders complete a paid weld test at our Hamilton shop."),
 J("j24","Pharmacy Assistant","e4","health","Calgary","AB","Part Time","On-site",21,25,"hr",6,"Entry level welcome","High School Diploma",10,"2 days ago",820,false,false,
  ["Prescription Intake","Inventory","Customer Service","Attention to Detail","POS Systems"],
  ["Colleague discount","Flexible part-time shifts","Paid training","Benefits at 20+ hours","Path to pharmacy technician"],
  "Support pharmacists with prescription intake, inventory and customer service in a busy community pharmacy. Full training provided with a clear path to a technician role.",
  ["Receive and enter prescriptions accurately","Manage stock levels and expiry checks","Assist customers at the counter and by phone","Process payments and insurance claims","Maintain a clean and organised dispensary"],
  ["High school diploma","Strong attention to detail and discretion","Comfortable on your feet for full shifts","Available some evenings and weekends","Previous retail or pharmacy experience an asset"],
  "Apply online with your resume. Interviews are held at the store location."),
 J("j25","Hotel Front Desk Agent","e5","hosp","Toronto","ON","Full Time","On-site",22,26,"hr",4,"Entry level welcome","High School Diploma",12,"5 days ago",740,false,false,
  ["Guest Service","PMS Systems","Cash Handling","Problem Solving","Communication"],
  ["Hotel discount worldwide","Meal allowance","Extended health after 3 months","Paid uniform","Cross-training opportunities"],
  "Welcome guests, manage reservations and resolve requests at a downtown property. Great entry point into hospitality with cross-training into other departments.",
  ["Check guests in and out efficiently","Manage reservations and room assignments","Handle payments and reconcile the float","Respond to guest requests and complaints","Coordinate with housekeeping and maintenance"],
  ["High school diploma","Excellent communication and composure","Available for overnight and weekend shifts","Comfortable with property management systems","Second language an asset"],
  "Apply online. Interviews include a short guest-scenario roleplay."),
 J("j26","Educational Assistant","e8","edu","Ottawa","ON","Full Time","On-site",24,30,"hr",7,"Entry level welcome","EA Certificate or equivalent",14,"3 days ago",930,false,false,
  ["Behaviour Support","Special Needs","Patience","Collaboration","First Aid"],
  ["Summers off","OMERS pension","Extended health","Paid professional development","School-day hours"],
  "Support students with additional needs in an inclusive classroom, working alongside teachers and specialists. Weekday school hours with summers off.",
  ["Support students individually and in small groups","Assist with personal care and mobility as needed","Implement behaviour and safety plans","Prepare materials and adapt activities","Communicate observations to the teaching team"],
  ["Educational Assistant certificate or related diploma","Vulnerable sector check","Standard First Aid and CPR-C","Patience and a calm, consistent manner","Experience supporting children an asset"],
  "Apply with your certificate. Interviews include a classroom scenario discussion."),
 J("j27","Fish Plant Production Worker","e10","agri","St. John's","NL","Seasonal","On-site",20,24,"hr",25,"No experience required","No formal education required",8,"1 day ago",610,true,false,
  ["Food Safety","Manual Dexterity","Team Work","Standing Long Periods","Reliability"],
  ["Overtime during peak season","Transportation subsidy","Gear provided","Seasonal bonus","Returning worker priority"],
  "Process and pack seafood on a modern production line. No experience required, full training provided, and consistent overtime through the peak season.",
  ["Trim, sort and pack product to quality standards","Operate processing equipment after training","Maintain sanitation and food safety standards","Record production counts","Support line changeovers"],
  ["Ability to stand for 8+ hours in a cold, wet environment","Comfortable with repetitive manual work","Reliable attendance","Steel-toed rubber boots required","No experience needed"],
  "Apply online or at the plant office. Hiring runs weekly through the season."),
 J("j28","Junior Accountant","e7","finance","Vancouver","BC","Full Time","Hybrid",54000,66000,"yr",2,"1+ years","Accounting Diploma or Degree",16,"4 days ago",1020,false,false,
  ["Excel","Reconciliation","Accounts Payable","QuickBooks","GAAP"],
  ["CPA program support","Hybrid 2 days remote","Pension matching","Annual bonus","Extended health from day one"],
  "Support month-end close, reconciliations and reporting in a growing finance team, with structured support toward your CPA designation.",
  ["Prepare journal entries and account reconciliations","Support month-end and year-end close","Process accounts payable and receivable","Assist with budget and variance reporting","Maintain accurate financial records"],
  ["Accounting diploma or degree","1+ years in an accounting role","Strong Excel skills","Working toward CPA an asset","High accuracy and attention to detail"],
  "Apply with your resume and CPA status. Assessment includes an Excel reconciliation task."),
 J("j29","Landscape Crew Lead","e12","agri","Kelowna","BC","Seasonal","On-site",26,32,"hr",5,"2+ years","No formal education required",7,"2 days ago",480,false,false,
  ["Crew Leadership","Equipment Operation","Horticulture","Scheduling","Safety"],
  ["Truck and equipment provided","Seasonal completion bonus","Overtime available","Boot allowance","Return-season priority"],
  "Lead a three-person crew on residential and commercial landscape installations across the Okanagan through the April to October season.",
  ["Lead daily crew scheduling and site setup","Operate skid steers, mowers and hand equipment","Install plantings, hardscape and irrigation","Enforce safety practices on every site","Communicate progress with the project manager"],
  ["2+ years landscape or grounds experience","Valid driver's licence, Class 5 minimum","Ability to lift 50 lb repeatedly","Leadership experience an asset","Comfortable working outdoors all season"],
  "Apply online with your resume. Interviews and site walkthroughs are held weekly."),
 J("j30","IT Support Technician","e9","tech","Calgary","AB","Full Time","Hybrid",52000,66000,"yr",3,"1+ years","College Diploma or certification",18,"3 days ago",1310,false,false,
  ["Windows","Active Directory","Ticketing Systems","Hardware Repair","Networking"],
  ["Certification reimbursement","Hybrid 3 days in office","RRSP matching","Full benefits","On-call premium"],
  "Provide first and second line technical support to internal staff across three Alberta offices, with a clear path into systems or network administration.",
  ["Resolve hardware, software and network tickets","Image and deploy laptops and mobile devices","Manage user accounts in Active Directory","Document solutions in the knowledge base","Escalate complex issues to senior staff"],
  ["1+ years IT support experience","Familiarity with Windows and Microsoft 365","CompTIA A+ or equivalent an asset","Strong communication with non-technical users","Valid driver's licence for site visits"],
  "Apply with your resume and certifications. Interviews include a short troubleshooting scenario."),
];

export const SEED_JOBS=[...FLAGSHIP_JOBS, ...EXTRA_JOBS];
