const TR=(id,title,cat,scene,tone,provider,providerSeed,level,hours,price,rating,enrolled,mods,outcomes,about,owner)=>
  ({id,title,cat,scene,tone,provider,providerSeed,level,hours,price,rating,enrolled,mods,outcomes,about,owner,status:"published",featured:false});

export const SEED_TRAININGS=[
 TR("t1","WHMIS 2015 & Workplace Safety Certification","Safety","safety","#8F5B05","NorthHire Learning",0,"Beginner",4,0,4.8,12840,
  ["Hazard classes and pictograms","Reading a Safety Data Sheet","Workplace labelling requirements","Employer and worker duties","Practical assessment and certificate"],
  ["Recognise all nine WHMIS hazard classes on sight","Locate and interpret any section of an SDS","Meet the training requirement most Canadian employers ask for","Receive a certificate valid across all provinces"],
  "The single most requested certificate on Canadian job postings. Required before you set foot on most industrial, warehouse, construction and healthcare sites. This course is free, takes an afternoon, and issues a certificate you can attach directly to your NorthHire profile.","admin"),
 TR("t2","Red Seal Exam Preparation — Electrician","Trades","trades","#B45309","NorthHire Learning",1,"Advanced",36,149,4.7,3120,
  ["Canadian Electrical Code navigation","Circuit calculations and load analysis","Motors, controls and transformers","Grounding and bonding","Two full-length practice exams with review"],
  ["Navigate the CE Code quickly under exam conditions","Work through load and conduit fill calculations reliably","Identify your weak task areas before exam day","Sit the Red Seal with two timed practice exams behind you"],
  "Built directly from the national occupational analysis for the electrician trade, so every module maps to a task the exam can test. Includes two timed practice exams with worked solutions and an instructor review session.","admin"),
 TR("t3","Food Handler Certification (FOODSAFE Level 1)","Hospitality","kitchen","#AE2119","NorthHire Learning",2,"Beginner",6,39,4.6,8940,
  ["Foodborne illness and contamination","Temperature control and the danger zone","Personal hygiene standards","Cleaning and sanitising","Provincial certification exam"],
  ["Meet the food handler requirement in every province","Apply temperature control confidently in a working kitchen","Pass the provincial certification exam","Add a recognised certificate to your profile"],
  "Required for kitchen, grocery, catering and long-term care food service roles across Canada. Recognised provincially and completed entirely online with an invigilated final exam.","admin"),
 TR("t4","Forklift Operator Certification","Warehouse","warehouse","#005CCC","NorthHire Learning",3,"Beginner",8,89,4.5,6210,
  ["Forklift classes and components","Stability triangle and load charts","Pre-operational inspection","Safe operating procedures","Practical evaluation"],
  ["Perform a complete pre-operational inspection","Calculate load capacity from a data plate","Operate a counterbalance lift safely","Hold certification accepted by Canadian employers"],
  "Theory delivered online with a practical evaluation booked at a partner site in your city. Warehouse and building-supply employers list this on the majority of their postings.","admin"),
 TR("t5","Personal Support Worker Fundamentals","Healthcare","care","#0F5C8C","NorthHire Learning",4,"Beginner",24,0,4.9,5480,
  ["Role of the PSW in Canadian care settings","Safe transfers and mobility support","Personal care and dignity","Recognising and reporting changes","Documentation and privacy"],
  ["Understand the PSW scope of practice","Perform safe transfers using proper body mechanics","Document care accurately and privately","Decide whether a full PSW certificate is right for you"],
  "A free introduction to personal support work for anyone considering the field. It does not replace a full PSW certificate, but it gives you an honest picture of the work and counts toward several partner college programs.","admin"),
 TR("t6","Class 1 Air Brake (Z) Endorsement Prep","Transport","road","#B02A26","NorthHire Learning",5,"Intermediate",12,119,4.4,2870,
  ["Air brake system components","Pre-trip air brake inspection","Adjustment and slack adjusters","Common defects and failures","Written test preparation"],
  ["Complete a full air brake pre-trip inspection out loud","Identify defects that will fail a road test","Pass the provincial written air brake test","Prepare for the practical examination"],
  "Covers the theory and the spoken pre-trip inspection that trips up most candidates on test day. Pairs with any provincial Class 1 program.","admin"),
 TR("t7","Interview Skills for Canadian Employers","Career","learn","#5B3BC4","NorthHire Learning",6,"Beginner",5,0,4.7,15230,
  ["What Canadian interviewers are assessing","Behavioural questions and the STAR method","Talking about pay","Questions worth asking them","Mock interview with feedback"],
  ["Answer behavioural questions with a clear structure","Discuss pay expectations without undercutting yourself","Prepare specific examples from your own work history","Practise with a recorded mock interview"],
  "Free and practical. Built around the questions Canadian employers actually ask, including how to handle the Canadian experience question if you trained abroad.","admin"),
 TR("t8","Working at Heights (Ontario approved)","Safety","safety","#07724F","NorthHire Learning",7,"Intermediate",8,159,4.6,4390,
  ["Legislation and employer duties","Fall protection equipment","Anchor points and connectors","Rescue planning","Practical harness assessment"],
  ["Select and inspect fall protection equipment correctly","Identify adequate anchor points on a site","Meet the Ontario MLITSD training requirement","Hold a certificate valid for three years"],
  "Ontario-approved Working at Heights training, mandatory for most construction work in the province. Theory online with a practical component at a partner training centre.","admin"),
 TR("t9","Excel for the Workplace","Office","office","#005CCC","NorthHire Learning",8,"Beginner",10,49,4.5,9120,
  ["Navigating and formatting efficiently","Formulas that matter at work","Lookups and conditional logic","PivotTables from scratch","Charts and clean reporting"],
  ["Build a working reconciliation from raw data","Use VLOOKUP, XLOOKUP and IF confidently","Summarise thousands of rows with a PivotTable","Produce a clean report a manager can read"],
  "The Excel that office, payroll, logistics and retail management roles actually require. Everything is taught on real workplace files rather than abstract exercises.","admin"),
 TR("t10","French for the Workplace (A1 to A2)","Language","learn","#2A3852","NorthHire Learning",9,"Beginner",30,79,4.3,3640,
  ["Workplace greetings and introductions","Describing your role and tasks","Handling customers and phone calls","Health, safety and instructions","Assessment and certificate"],
  ["Hold a basic workplace conversation in French","Take a customer call with confidence","Understand safety instructions in French","Meet the working-French bar for many Quebec roles"],
  "Aimed at workers who need functional French for a Quebec or bilingual role rather than academic study. Practical vocabulary organised by sector.","admin"),
];
