/* ═══════════════ ROUTE MAP + SHELL ═══════════════ */
/* roles: null = everyone. tab = which bottom tab lights up. root = show logo on mobile. */
export const ROUTES = {
  home:        {title:"Home", tab:"home", root:true},
  matched:     {title:"Matched jobs", tab:"matched", root:true, roles:["seeker"]},
  search:      {title:"Search jobs", tab:"search", root:true},
  status:      {title:"My status", tab:"status", root:true, roles:["seeker"]},
  profile:     {title:"Profile", tab:"profile", root:true},

  job:         {title:"Job details", tab:"search"},
  employer:    {title:"Employer", tab:"search"},
  apply1:      {title:"Apply · Your profile", tab:"search", roles:["seeker"]},
  apply2:      {title:"Apply · Questions", tab:"search", roles:["seeker"]},
  apply3:      {title:"Apply · Review", tab:"search", roles:["seeker"]},
  applyDone:   {title:"Application sent", tab:"search", roles:["seeker"]},

  saved:       {title:"Saved jobs", tab:"status", roles:["seeker"]},
  savedSearches:{title:"Saved searches", tab:"status", roles:["seeker"]},
  messages:    {title:"Messages", tab:"alerts", roles:["seeker","employer"]},
  interviews:  {title:"Interviews", tab:"alerts", roles:["seeker","employer"]},
  empAnalytics:{title:"Analytics", tab:"empHome", roles:["employer"], bare:true, root:true},
  alerts:      {title:"Notifications", tab:"status"},
  cvs:         {title:"My CVs", tab:"profile", roles:["seeker"]},
  cvEdit:      {title:"CV builder", tab:"profile", roles:["seeker"]},
  settings:    {title:"Settings", tab:"profile"},

  blogs:       {title:"Career resources", tab:"home"},
  blog:        {title:"Article", tab:"home"},
  trainings:   {title:"Trainings", tab:"home"},
  training:    {title:"Training details", tab:"home"},
  employers:   {title:"Employers", tab:"search"},

  about:       {title:"About us", tab:"home"},
  contact:     {title:"Contact us", tab:"home"},
  privacy:     {title:"Privacy policy", tab:"home"},
  terms:       {title:"Terms of service", tab:"home"},
  pricing:     {title:"Pricing", tab:"home"},
  forEmployers:{title:"For employers", tab:"home"},
  howItWorks:  {title:"How it works", tab:"home"},
  forgot:      {title:"Reset password", tab:"home", bare:true},
  welcome:     {title:"Welcome to NorthHire", tab:"home", bare:true, root:true},
  welcomeEmp:  {title:"Welcome to NorthHire", tab:"matched", bare:true, root:true},
  account:     {title:"My account", tab:"profile", roles:["seeker"]},
  accessibility:{title:"Accessibility (AODA)", tab:"home", root:false},
  pipeda:       {title:"PIPEDA compliance", tab:"home", root:false},
  /* HR Suite routes */
  hrLogin:      {title:"HR Suite login", tab:"home", bare:true},
  hrDashboard:  {title:"Dashboard", tab:"home", bare:true},
  hrDirectory:  {title:"Directory", tab:"home", bare:true},
  hrProfile:    {title:"My profile", tab:"home", bare:true},
  hrAttendance: {title:"Attendance", tab:"home", bare:true},
  hrLeave:      {title:"Leave", tab:"home", bare:true},
  hrTasks:      {title:"Tasks", tab:"home", bare:true},
  hrCalendar:   {title:"Calendar", tab:"home", bare:true},
  hrChat:       {title:"Chat", tab:"home", bare:true},
  hrTrainings:  {title:"Trainings", tab:"home", bare:true},
  hrBadges:     {title:"Badges", tab:"home", bare:true},
  hrPeople:     {title:"People", tab:"home", bare:true},
  hrExpenses:   {title:"Expenses", tab:"home", bare:true},
  hrHiring:     {title:"Hiring", tab:"home", bare:true},
  hrInvoices:   {title:"Invoices", tab:"home", bare:true},
  hrPayroll:    {title:"Payroll", tab:"home", bare:true},
  hrReports:    {title:"Reports", tab:"home", bare:true},
  hrSettings:   {title:"HR Settings", tab:"home", bare:true},
  hrIntegrations:{title:"Integrations", tab:"home", bare:true},

  /* ─── Staffing agency console ─── */
  agencyLogin:      {title:"Agency sign in", tab:"home", bare:true},
  agencyDashboard:  {title:"Agency dashboard", tab:"home", bare:true, root:true},
  agencyJobOrders:  {title:"Job orders", tab:"home", bare:true, root:true},
  agencyBench:      {title:"Bench", tab:"home", bare:true, root:true},
  agencyAssignments:{title:"Assignments", tab:"home", bare:true, root:true},
  agencyTimesheets: {title:"Timesheets", tab:"home", bare:true, root:true},
  agencyPayroll:    {title:"Staffing payroll", tab:"home", bare:true, root:true},
  agencyInvoicing:  {title:"Invoicing", tab:"home", bare:true, root:true},
  agencyPlacements: {title:"Placements", tab:"home", bare:true, root:true},
  agencyClients:    {title:"Clients", tab:"home", bare:true, root:true},
  agencyWorkers:    {title:"Workers", tab:"home", bare:true, root:true},
  agencyMargins:    {title:"Margins", tab:"home", bare:true, root:true},
  agencyCompliance: {title:"Compliance", tab:"home", bare:true, root:true},

  /* ─── Worker view (seeker who opted in) ─── */
  workerDashboard:  {title:"Worker dashboard", tab:"profile", roles:["seeker"]},
  workerTimesheet:  {title:"Weekly timesheet", tab:"profile", roles:["seeker"]},
  workerPayStubs:   {title:"Pay stubs", tab:"profile", roles:["seeker"]},
  workerDocuments:  {title:"My documents", tab:"profile", roles:["seeker"]},

  /* ─── Client staffing tab (employer inside their console) ─── */
  empStaffing:            {title:"Staffing", tab:"home", roles:["employer"], bare:true, root:true},
  empStaffingRequests:    {title:"Job requests", tab:"home", roles:["employer"], bare:true, root:true},
  empStaffingAssignments: {title:"Active assignments", tab:"home", roles:["employer"], bare:true, root:true},
  empStaffingTimesheets:  {title:"Approve timesheets", tab:"home", roles:["employer"], bare:true, root:true},
  empStaffingInvoices:    {title:"Staffing invoices", tab:"home", roles:["employer"], bare:true, root:true},

  login:       {title:"Sign in", tab:"profile", bare:true},
  signup:      {title:"Create account", tab:"profile", bare:true},

  empHome:     {title:"Employer dashboard", tab:"home", roles:["employer"], root:true, bare:true},
  empJobs:     {title:"My job listings", tab:"search", roles:["employer"], bare:true, root:true},
  empPost:     {title:"Post a job", tab:"search", roles:["employer"], bare:true, root:true},
  empPipeline: {title:"Candidates", tab:"status", roles:["employer"], root:true, bare:true},
  empCandidate:{title:"Candidate", tab:"status", roles:["employer"], bare:true, root:true},
  empContent:  {title:"Content", tab:"matched", roles:["employer"], root:true, bare:true},
  empArticles: {title:"Articles", tab:"matched", roles:["employer"], root:true, bare:true},
  empTrainings:{title:"Trainings", tab:"matched", roles:["employer"], root:true, bare:true},
  empBlogEdit: {title:"Edit article", tab:"matched", roles:["employer","admin"]},
  empTrainEdit:{title:"Edit training", tab:"matched", roles:["employer","admin"]},
  empCompany:  {title:"Company profile", tab:"profile", roles:["employer"], bare:true, root:true},
  empBilling:  {title:"Billing", tab:"profile", roles:["employer"], bare:true, root:true},

  admHome:     {title:"Admin overview", tab:"home", roles:["admin"], root:true, bare:true},
  admUsers:    {title:"Users", tab:"search", roles:["admin"], bare:true, root:true},
  admEmployers:{title:"Employers", tab:"search", roles:["admin"], bare:true, root:true},
  admJobs:     {title:"Job moderation", tab:"status", roles:["admin"], root:true, bare:true},
  admBlogs:    {title:"Articles", tab:"matched", roles:["admin"], root:true, bare:true},
  admTrainings:{title:"Trainings", tab:"matched", roles:["admin"], bare:true, root:true},
  admSettings: {title:"Platform settings", tab:"profile", roles:["admin"], bare:true, root:true},
  admLog:      {title:"Activity log", tab:"profile", roles:["admin"], bare:true, root:true},
  admStats:    {title:"Platform statistics", tab:"profile", roles:["admin"], bare:true, root:true},

  denied:      {title:"Not available", tab:"home"},
};

export const TABS_BY_ROLE = {
  guest:    [["home","Home","home"],["search","Jobs","search"],["trainings","Trainings","cap"],["blogs","Resources","book"],["login","Sign in","user"]],
  seeker:   [["home","Home","home"],["matched","Matched","target"],["search","Search","search"],["status","Status","activity"],["account","Profile","user"]],
  employer: [["empHome","Home","home"],["empJobs","Jobs","briefcase"],["empPost","Post","plus"],["empPipeline","Candidates","users"],["empCompany","Profile","building"]],
  admin:    [["admHome","Home","home"],["admBlogs","Content","book"],["admUsers","People","users"],["admJobs","Moderation","shield"],["admSettings","Settings","gear"]],
};
